### ISSUE TITLE
+ '/trunk/NDHMS' ?

### ISSUE THREAD

**Issue by jmccreight** [NCAR/wrf_hydro_py#23]
I find it that WrfHydroModel fails when I point it to the top level of the repo and that I have to specify the /trunk/NDHMS/. It would be preferable to point it to the repo top.

**Comment by jmills-ncar** [comment]
My rational there was not to perpetuate the idea of wrf_hydro_nwm being the ‘source directory’ since nothing resides in that top level directory except a couple of boiler plate items. Additionally, by default everything is compiled into the NDHMS directory, so really it is the one we should point to

**Comment by jmills-ncar** [comment]
I see if being wrf_hydro_nwm/tests , wrf_hydro_nwm/docs, wrf_hydro_nwm/trunk, etc

**Comment by jmccreight** [comment]
At least for a model compile method I think it could fill in the blank.  a test method could go to test/

**Comment by jmills-ncar** [comment]
making an executive decision on this one
